from typing import List

SEED = 111
MAX_LAGS = 57
START_DAY = 300
num_boost_round = 2500
MIN_SUM = 1


lgbm_params = {
    "boosting_type": "gbdt",
    "metric": "rmse",
    "objective": "poisson",
    "n_jobs": -1,
    "seed": SEED,
    # "max_depth": 300,
    "num_leaves": 2 ** 7 - 1,
    "min_data_in_leaf": 50,
    "learning_rate": 0.05,
    "bagging_freq": 1,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.75,
}

features = [
    # "id",
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id",
    # "d",
    # "sales",
    # "release",
    # "wm_yr_wk",
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "cal_christmas_eve",
    "cal_christmas",
    "cal_blackfriday",
    "event_name_1_yesterday",
    "event_type_1_yesterday",
    "event_name_1_tomorrow",
    "event_type_1_tomorrow",
    "snap",
    "tm_d",
    "tm_w",
    "tm_wday",
    "tm_m",
    "tm_y",
    "tm_quarter",
    "tm_wm",
    "tm_wy",
    "tm_dw",
    "tm_w_end",
    "sell_price",
    "fe_price_max",
    "fe_price_min",
    "fe_price_std",
    "fe_price_mean",
    "fe_price_discount",
    "fe_price_discount_rate",
    "fe_price_skew",
    "fe_price_kurt",
    "fe_price_norm",
    "fe_price_nunique",
    "fe_price_item_nunique",
    "fe_price_momentum",
    "fe_price_momentum_m",
    "fe_price_momentum_y",
    "shift_t1",
    "shift_t2",
    "shift_t3",
    "shift_t4",
    "shift_t5",
    "shift_t6",
    "shift_t7",
    # "shift_t8",
    "shift_t14",
    # "shift_t15",
    "shift_t28",
    # "shift_t29",
    # "shift_t30",
    # "shift_t31",
    # "shift_t32",
    # "shift_t33",
    # "shift_t34",
    # "shift_t338",
    # "shift_t339",
    # "fe_rolling_sum_t1_30",
    # "fe_rolling_sum_t1_50",
    "fe_rolling_mean_t1_7",
    "fe_rolling_mean_t1_30",
    "fe_rolling_mean_t1_60",
    "fe_rolling_mean_t1_90",
    "fe_rolling_mean_t1_180",
    "fe_rolling_mean_t7_7",
    "fe_rolling_mean_t7_30",
    "fe_rolling_mean_t7_60",
    "fe_rolling_mean_t7_90",
    "fe_rolling_mean_t7_180",
    # "fe_rolling_mean_t14_7",
    # "fe_rolling_mean_t14_30",
    # "fe_rolling_mean_t14_60",
    # "fe_rolling_mean_t14_90",
    # "fe_rolling_mean_t14_180",
    "fe_rolling_mean_t28_7",
    "fe_rolling_mean_t28_30",
    "fe_rolling_mean_t28_60",
    "fe_rolling_mean_t28_90",
    "fe_rolling_mean_t28_180",
    "fe_rolling_std_t7_7",
    "fe_rolling_std_t7_30",
    "fe_rolling_std_t7_60",
    "fe_rolling_std_t7_90",
    "fe_rolling_std_t7_180",
    # "fe_rolling_std_t14_7",
    # "fe_rolling_std_t14_30",
    # "fe_rolling_std_t14_60",
    # "fe_rolling_std_t14_90",
    # "fe_rolling_std_t14_180",
    "fe_rolling_std_t28_7",
    "fe_rolling_std_t28_30",
    "fe_rolling_std_t28_60",
    "fe_rolling_std_t28_90",
    "fe_rolling_std_t28_180",
    "fe_rolling_kurt_t28_30",
    "fe_rolling_skew_t28_30",
    "fe_price_change_t1",
    "fe_price_change_t365",
    "fe_rolling_price_std_t7",
    "fe_rolling_price_std_t30",
    # "fe_revenue",
    # "fe_revenue_dept_sum",
]

features = [
    "item_id",
    "dept_id",
    "cat_id",
    "store_id",
    "state_id",
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2",
    "event_name_1_yesterday",
    "event_type_1_yesterday",
    "event_name_1_tomorrow",
    "event_type_1_tomorrow",
    "snap_CA",
    "snap_TX",
    "snap_WI",
    "tm_d",
    "tm_w",
    "tm_wday",
    "tm_m",
    "tm_y",
    "tm_quarter",
    "tm_wm",
    "tm_wy",
    "tm_dw",
    "sell_price",
    "fe_price_max",
    "fe_price_std",
    "fe_price_mean",
    "fe_price_discount",
    "fe_price_discount_rate",
    "shift_t7",
    "shift_t28",
    "shift_t29",
    "shift_t30",
    "fe_rolling_mean_t7_7",
    "fe_rolling_mean_t7_30",
    "fe_rolling_mean_t28_7",
    "fe_rolling_std_t28_7",
    "fe_rolling_mean_t28_30",
    "fe_rolling_std_t28_30",
    "fe_rolling_mean_t28_90",
    "fe_rolling_mean_t28_180",
    "fe_rolling_skew_t28_30",
    "fe_rolling_kurt_t28_30",
    "fe_price_change_t1",
    "fe_price_change_t365",
    "fe_rolling_price_std_t7",
    "fe_rolling_price_std_t30",
]


lgbm_cat_features: List[str] = [
    f
    for f in features
    if f
    in [
        "item_id",
        "dept_id",
        "cat_id",
        "store_id",
        "state_id",
        "event_name_1",
        "event_type_1",
        "event_name_2",
        "event_type_2",
        "event_name_1_yesterday",
        "event_type_1_yesterday",
        "event_name_1_tomorrow",
        "event_type_1_tomorrow",
        "snap",
        "snap_CA",
        "snap_TX",
        "snap_WI",
    ]
]
